/*
SQLyog Enterprise - MySQL GUI v8.1 
MySQL - 5.5.16 : Database - tcgn
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`tcgn` /*!40100 DEFAULT CHARACTER SET latin1 */;

/*Table structure for table `battle` */

DROP TABLE IF EXISTS `battle`;

CREATE TABLE `battle` (
  `BATTLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATTLE_PLAYER_1` int(11) DEFAULT NULL,
  `BATTLE_PLAYER_2` int(11) DEFAULT NULL,
  `BATTLE_TIME` datetime DEFAULT NULL,
  `BATTLE_WINNER` int(11) DEFAULT NULL,
  PRIMARY KEY (`BATTLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `card` */

DROP TABLE IF EXISTS `card`;

CREATE TABLE `card` (
  `CARD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CARD_NAME` varchar(255) DEFAULT NULL,
  `CARD_DESCRIPTION` varchar(255) DEFAULT NULL,
  `CARD_STRENGTH` int(11) DEFAULT '0',
  `CARD_DEFENSE` int(11) DEFAULT '0',
  `CARD_HP` int(11) DEFAULT '0',
  `CARD_LEVEL` int(11) DEFAULT '0',
  `CARD_TIPE` int(11) DEFAULT '0',
  `CARD_MAGIC_NUMBER` int(11) DEFAULT '0',
  `ENCHANT_STRENGTH` int(11) DEFAULT '0',
  `ENCHANT_DEFENSE` int(11) DEFAULT '0',
  `ENCHANT_HP` int(11) DEFAULT '0',
  `CARD_PRICE` decimal(10,0) DEFAULT '0',
  PRIMARY KEY (`CARD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `player` */

DROP TABLE IF EXISTS `player`;

CREATE TABLE `player` (
  `PLAYER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLAYER_NAME` varchar(255) DEFAULT NULL,
  `PLAYER_PASSWORD` varchar(255) DEFAULT NULL,
  `PLAYER_WIN` int(11) DEFAULT '0',
  `PLAYER_LOSE` int(11) DEFAULT '0',
  `PLAYER_MONEY` decimal(10,0) DEFAULT '0',
  PRIMARY KEY (`PLAYER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `player_card` */

DROP TABLE IF EXISTS `player_card`;

CREATE TABLE `player_card` (
  `PLAYER_CARD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CARD_ID` int(11) DEFAULT NULL,
  `PLAYER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PLAYER_CARD_ID`),
  KEY `CARD_ID` (`CARD_ID`),
  KEY `PLAYER_ID` (`PLAYER_ID`),
  CONSTRAINT `FKFFD76B2A96048B6C` FOREIGN KEY (`PLAYER_ID`) REFERENCES `player` (`PLAYER_ID`),
  CONSTRAINT `FKFFD76B2A6A370C40` FOREIGN KEY (`CARD_ID`) REFERENCES `card` (`CARD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
